### ISSUE TITLE
Support for working-directory: parameter

### ISSUE THREAD

**Issue by jni** [aganders3/headless-gui#1]
GabrielBB/xvfb-action [supported](https://github.com/GabrielBB/xvfb-action#example-usage) an optional `working-directory:` to run commands in a different directory from the root. This can be important to set for certain commands such as running jupyter notebooks, because `run: cd some-dir` doesn't work. It would be good for headless-gui to support this argument as well! 🙏

**Comment by aganders3** [comment]
Thanks for the report! Indeed I left this out as I hadn't seen it used, but that makes sense.

Is it sufficient to run only commands from the `run` section with this working directory (i.e. not the setup/teardown commands)?

Also I realize now I've been using snake_case for the inputs, so to keep it consistent I'd like to use `working_dir` (or `workding_directory`). Unfortunately this means it's not quite drop-in to replace xfvb-action.

**Comment by jni** [comment]
> Also I realize now I've been using snake_case for the inputs, so to keep it consistent I'd like to use working_dir (or working_directory). Unfortunately this means it's not quite drop-in to replace xfvb-action.

imho being a drop-in replacement should be a goal of this project... You don't think there's time to reverse this decision? I have weak feelings about this, but they point in the direction of aiming for that.

**Comment by aganders3** [comment]
No, I think that's fine at least for any existing options (e.g. `working-directory`).

What I don't want to do is replace the other commands (`linux_pkgs`, etc.) with kebab-case as there are already a number of repos that would need to change. It would be a shame to have a breaking change so soon.

I tend to prefer snake_case but will see if there's a strong convention in GitHub Actions or yaml this should be following and allow for migration.

I will update my PR and tag you for review.
